///////////////////////////////////////////////////////////
//  Konstantat.cs
//  Implementation of the Class Konstantat
//  Generated by Enterprise Architect
//  Created on:      12-Aug-2006 9:03:46 AM
//  Original author: Veton Shala
///////////////////////////////////////////////////////////
using System;
using System.Configuration;
using System.Data.SqlClient;

namespace MyNET.DAL
{
    public class Constants
    {
        protected static string mDatabase;
        protected static string mServer;


        public static string Database
        {
            get { return mDatabase; }
            set { mDatabase = value; }
        }

        public static string Server
        {
            get { return mServer; }
            set { mServer = value; }
        }


        public Constants()
        {
            //
            // TODO: AddWithValue Constructor Logic here
            //
        }

        public static string Connectionstr()  
        {
            string strcon = ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString;
            strcon = strcon.Replace("dbname", mDatabase);
            strcon = strcon.Replace("server", mServer);
            return strcon;

            //string strcnnString = ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString;
            //return strcnnString;
            //string cnnstr = @"server=DELL\SQLExpress;database=ppcit;user=sa;pwd=sonata";
            //return cnnstr;
        }

        public static string Connectionstr2()
        {
            string strcon = ConfigurationManager.ConnectionStrings["ConnectionString2"].ConnectionString;           
            return strcon;
            //string strcnnString = ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString;
            //return strcnnString;
            //string cnnstr = @"server=DELL\SQLExpress;database=ppcit;user=sa;pwd=sonata";
            //return cnnstr;
        }

        public static bool TestConnection(string server)
        {
            bool retVal = false;
            try
            {
                string strcon = ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString;
                strcon = strcon.Replace("server", server);
                SqlConnection cnn = new SqlConnection(strcon);
                cnn.Open();
                
                retVal = true;
            }
            catch(Exception ex)
            {
                //todo: log error on conn with servre
            }
            return retVal;           
        }
    }

}//end namespace MyNET.DAL
